# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Gruvbox
license = "GNU General Public License v3.0"
licenselink = "https://github.com/deadl0ckio/hugo-grubox-theme/blob/main/LICENSE"
description = "Gruvbox theme for Hugo"
homepage = "https://github.com/deadl0ckio/hugo-grubox-theme"
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = 0.14

[author]
  name = "deadl0ck"
  homepage = "https://github.com/deadl0ckio"
